package ch9.test;

public class Exception3Test {

	public static void main(String[] args) {
		try {
			System.out.println("no exception");
		} catch(NullPointerException e) {
			System.out.println("lullluulllululululululu  no exception");
		} finally {
			System.out.println("no exception finally");
		}
		
	}
}
